import { StyleSheet, Platform } from 'react-native';
import { theme } from '../theme';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: theme.bg, paddingTop: Platform.OS === 'android' ? 35 : 0 },
  container: { flex: 1, backgroundColor: theme.bg },
  header: { padding: 24, paddingBottom: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  greeting: { fontSize: 26, fontWeight: '800', color: theme.text, marginBottom: 4 },
  statusRowNew: { flexDirection: 'row', marginTop: 4, flexWrap: 'wrap' },
  statusPill: { flexDirection: 'row', alignItems: 'center', backgroundColor: theme.surface, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, marginRight: 8, marginTop: 4, borderWidth: 1, borderColor: theme.surfaceHighlight },
  statusText: { color: theme.textHighContrast, fontSize: 12, marginLeft: 6, fontWeight: '600' },
  profileBadge: { width: 44, height: 44, borderRadius: 22, backgroundColor: theme.surface, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: theme.surfaceHighlight, marginTop: 4 },
  profileText: { color: theme.primary, fontSize: 18, fontWeight: 'bold' },
  onbContainer: { flex: 1, backgroundColor: theme.bg, alignItems: 'center', justifyContent: 'center' },
  onbCard: { width: '85%', backgroundColor: theme.surface, borderRadius: 24, padding: 30, alignItems: 'center' },
  onbTitle: { fontSize: 24, fontWeight: 'bold', color: '#FFF', marginBottom: 10 },
  onbText: { fontSize: 16, color: theme.textDim, textAlign: 'center', marginBottom: 20 },
  onbInput: { width: '100%', backgroundColor: '#000', color: '#FFF', padding: 16, borderRadius: 12, fontSize: 18, marginBottom: 20, textAlign: 'center' },
  onbBtn: { backgroundColor: theme.primary, paddingHorizontal: 32, paddingVertical: 16, borderRadius: 30, marginTop: 10, alignItems: 'center' },
  onbBtnText: { color: '#000', fontWeight: 'bold', fontSize: 18 },
  phraseRow: { padding: 16, borderBottomWidth: 1, borderBottomColor: theme.surfaceHighlight, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  phraseText: { color: theme.text, fontSize: 18 },
  sentenceContainer: { marginHorizontal: 24, marginBottom: 16, height: 70, backgroundColor: '#0F1623', borderRadius: 16, borderWidth: 1, borderColor: theme.primary, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, justifyContent:'space-between' },
  wordBubble: { backgroundColor: theme.surfaceHighlight, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 8, marginRight: 8, height: 46, justifyContent: 'center' },
  wordText: { color: theme.text, fontSize: 16, fontWeight: '600' },
  placeholderText: { color: theme.textDim, fontStyle: 'italic', marginLeft: 8 },
  editToolbar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: theme.surface, padding: 12, marginHorizontal: 24, borderRadius: 16, marginBottom: 16, borderWidth: 1, borderColor: theme.primary },
  editInfo: { flex: 1 },
  editLabel: { color: theme.textDim, fontSize: 10, fontWeight: 'bold', textTransform: 'uppercase' },
  editWord: { color: theme.primary, fontSize: 16, fontWeight: 'bold' },
  editActions: { flexDirection: 'row' },
  editBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: theme.surfaceHighlight, justifyContent: 'center', alignItems: 'center', marginLeft: 8 },
  scrollContent: { paddingHorizontal: 24 },
  section: { marginBottom: 32 },
  label: { color: theme.textDim, fontSize: 12, fontWeight: '700', marginBottom: 12, letterSpacing: 1.2 },
  inputLabel: { color: theme.textDim, fontSize: 12, fontWeight: '700', marginBottom: 8, letterSpacing: 1.2 },
  
  // GALLERY & GRID FIXES
  catGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  catTile: { width: '48%', backgroundColor: theme.surface, padding: 20, borderRadius: 20, marginBottom: 16, height: 110, justifyContent: 'space-between' },
  catTitle: { color: theme.text, fontSize: 16, fontWeight: 'bold' },
  galleryBannerLarge: { width: '100%', backgroundColor: theme.primary, borderRadius: 20, padding: 24, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  galleryIconBadge: { width: 48, height: 48, borderRadius: 24, backgroundColor: 'rgba(255,255,255,0.2)', justifyContent:'center', alignItems:'center', marginRight: 16 },
  galleryBannerText: { color: '#FFF', fontSize: 22, fontWeight: 'bold' },
  galleryGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  addPhotoCard: { width: '48%', aspectRatio: 1, backgroundColor: theme.surfaceHighlight, borderRadius: 16, justifyContent: 'center', alignItems: 'center', marginBottom: 16, borderStyle: 'dashed', borderWidth: 2, borderColor: theme.primary },
  photoCard: { width: '48%', aspectRatio: 1, backgroundColor: theme.surface, borderRadius: 16, padding: 8, marginBottom: 16 },
  photoPlaceholder: { flex: 1, borderRadius: 8, marginBottom: 8 },
  photoCaption: { color: '#FFF', fontWeight: 'bold', flex: 1, marginRight: 4 },

  listItemRow: { flexDirection: 'row', backgroundColor: theme.surfaceHighlight, padding: 12, borderRadius: 8, marginBottom: 8, alignItems: 'center' },
  
  // FIXED BOTTOM NAV (NEW)
  fixedBottomNav: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 85, backgroundColor: '#162032', borderTopWidth: 1, borderTopColor: theme.surfaceHighlight, flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', paddingBottom: 10, paddingHorizontal: 10 },
  navBtn: { alignItems: 'center', flex: 1, paddingVertical: 10 },
  navBtnPrimary: { backgroundColor: theme.primary, borderRadius: 16, flex: 1.2, marginHorizontal: 5, paddingVertical: 10, height: 60, justifyContent: 'center', transform: [{translateY: -5}] },
  navIconContainer: { marginBottom: 4 },
  navLabel: { fontSize: 11, color: theme.textDim, fontWeight: '600' },
  navLabelPrimary: { fontSize: 12, color: '#000', fontWeight: 'bold' },

  outputBar: { position: 'absolute', bottom: 30, left: 24, right: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  outputActions: { flexDirection: 'row', backgroundColor: '#162032', borderRadius: 30, padding: 6, shadowColor: "#000", shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.5, shadowRadius: 20, elevation: 10 },
  outputBtn: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 16, borderRadius: 24, marginLeft: 6 },
  outputBtnTextDark: { color: '#000', fontWeight: 'bold', marginLeft: 6 },
  outputBtnText: { color: '#FFF', fontWeight: 'bold', marginLeft: 6 },
  outputBtnDestructive: { width: 50, height: 50, borderRadius: 25, backgroundColor: theme.surfaceHighlight, justifyContent: 'center', alignItems: 'center' },
  
  emergencyContainer: { flex: 1, backgroundColor: theme.emergencyBg },
  emergencyHeader: { padding: 24, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  emergencyTitle: { color: theme.danger, fontSize: 24, fontWeight: '900', marginLeft: 16 },
  emergencyCard: { backgroundColor: theme.emergencyCard, padding: 20, borderRadius: 16, marginBottom: 20 },
  emLabel: { color: 'rgba(255,255,255,0.7)', fontSize: 12, fontWeight: 'bold', marginBottom: 4 },
  emValue: { color: '#FFF', fontSize: 20, fontWeight: 'bold', marginBottom: 4 },
  emValueSub: { color: '#EEE', fontSize: 16 },
  call112Btn: { backgroundColor: theme.danger, padding: 20, borderRadius: 16, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginBottom: 16 },
  callText: { color: '#FFF', fontSize: 24, fontWeight: '900', marginLeft: 16 },
  callBtnSmall: { flex:1, backgroundColor: theme.surfaceHighlight, padding: 16, borderRadius: 16, alignItems: 'center', marginRight: 10 },
  callSmallText: { color: '#FFF', fontWeight: 'bold', marginTop: 8 },
  medLabel: { color: theme.danger, fontWeight: 'bold', marginTop: 20, marginBottom: 4 },
  medValue: { color: '#000', fontSize: 16 },
  historyItem: { paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: theme.surfaceHighlight },
  historyTime: { color: theme.primary, fontSize: 12, marginBottom: 4 },
  historyText: { color: '#FFF', fontSize: 16 },
  emptyText: { color: theme.textDim, fontSize: 16, fontStyle: 'italic' },
  aiFullSentenceBtn: { backgroundColor: theme.surfaceHighlight, padding: 16, borderRadius: 12, marginBottom: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  aiFullSentenceText: { color: '#FFF', fontSize: 16, fontWeight: '600' },
  aiBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: theme.surfaceHighlight, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, marginRight: 10 },
  aiBadgeText: { color: theme.textDim, fontWeight: 'bold', fontSize: 10, marginLeft: 4 },
  selectorItem: { alignItems: 'center', marginRight: 24, opacity: 0.5 },
  selectorItemActive: { opacity: 1 },
  selectorIcon: { width: 60, height: 60, borderRadius: 30, backgroundColor: theme.surfaceHighlight, justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  selectorLabel: { color: '#FFF', fontWeight: 'bold' },
  formLabel: { color: theme.primary, fontWeight: 'bold', marginBottom: 8, marginTop: 16 },
  inputField: { backgroundColor: theme.surface, color: '#FFF', padding: 16, borderRadius: 12, fontSize: 16, marginBottom: 16 },
  quickBtn: { backgroundColor: theme.surface, paddingHorizontal: 20, paddingVertical: 16, borderRadius: 12, marginRight: 10, borderWidth:1, borderColor: theme.surfaceHighlight },
  quickText: { color: '#FFF', fontWeight:'bold', fontSize: 16 },
  addPhraseBtn: { flexDirection:'row', alignItems:'center', backgroundColor: theme.surfaceHighlight, padding: 16, borderRadius: 12, marginBottom: 20 },
  addPhraseText: { color: theme.text, fontWeight:'bold', marginLeft: 10 },
  catHeaderSmall: { fontSize: 20, fontWeight:'bold', color:'#FFF' },
  catHeaderBig: { fontSize: 28, fontWeight:'bold', color:'#FFF', marginBottom: 20 },
  builderContainerFull: { flex:1, backgroundColor: theme.bg, padding: 24 },
  builderHeader: { flexDirection:'row', justifyContent:'space-between', alignItems:'center', marginBottom: 20 },
  builderPreview: { backgroundColor: theme.surface, minHeight: 80, borderRadius: 16, justifyContent:'center', marginBottom: 20, padding: 10 },
  builderWordChip: { backgroundColor: theme.surfaceHighlight, paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8, marginHorizontal: 4 },
  aiMagicBtnFull: { backgroundColor: theme.primary, borderRadius: 12, padding: 12, flexDirection:'row', justifyContent:'space-between', alignItems:'center', marginBottom: 15 },
  aiMagicTextFull: { fontWeight:'bold', fontSize: 16 },
  suggestionBubble: { backgroundColor: theme.surfaceHighlight, paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, marginRight: 8, borderWidth:1, borderColor: theme.primary },
  suggestionText: { color: '#FFF' },
  wordTabs: { flexDirection:'row', marginBottom: 15 },
  wordTab: { flex:1, alignItems:'center', paddingVertical: 10, borderBottomWidth: 2, borderBottomColor: theme.surfaceHighlight },
  wordTabText: { color: theme.textDim, fontWeight:'bold', fontSize: 12 },
  coreWordsGrid: { flexDirection:'row', flexWrap:'wrap', justifyContent:'space-between' },
  coreWordTileLarge: { width:'48%', backgroundColor: theme.surface, padding: 20, borderRadius: 12, marginBottom: 12, alignItems:'center' },
  coreWordTextLarge: { color:'#FFF', fontSize: 18, fontWeight:'bold' },
  builderInputSmall: { flex:1, backgroundColor: theme.surface, borderRadius: 25, paddingHorizontal: 20, color:'#FFF', height: 50 },
  addBtnSmallRound: { width: 50, height: 50, borderRadius: 25, backgroundColor: theme.primary, justifyContent:'center', alignItems:'center', marginLeft: 10 },
  saveBtn: { backgroundColor: theme.primary, padding: 16, borderRadius: 16, alignItems:'center', marginTop: 10 },
  saveBtnText: { fontWeight:'bold', fontSize: 18 },
  fullScreenContainer: { flex:1, backgroundColor:'#000', justifyContent:'center', alignItems:'center', padding: 20 },
  fullScreenClose: { position:'absolute', top: 50, right: 30, alignItems:'center' },
  fullScreenContent: { transform: [{ rotate: '90deg'}] },
  fullScreenText: { color:'#FFF', fontSize: 50, fontWeight:'bold', textAlign:'center' },
  modalOverlay: { flex:1, backgroundColor:'rgba(0,0,0,0.8)', justifyContent:'flex-end' },
  selectorContainer: { backgroundColor: theme.bg, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, maxHeight: '80%' },
  selectorHeader: { flexDirection:'row', justifyContent:'space-between', alignItems:'center', marginBottom: 24 },
  selectorTitle: { color:'#FFF', fontSize: 20, fontWeight:'bold' },
  menuItem: { flexDirection:'row', alignItems:'center', paddingVertical: 16, borderBottomWidth:1, borderBottomColor: theme.surfaceHighlight },
  menuItemTitle: { color:'#FFF', fontSize: 18, marginLeft: 16, fontWeight:'bold' },
  tagContainer: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 10 },
  tagChip: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, backgroundColor: theme.surfaceHighlight, marginRight: 8, marginBottom: 8, borderWidth: 1, borderColor: theme.surfaceHighlight },
  tagChipActive: { backgroundColor: theme.primary, borderColor: theme.primary },
  tagText: { color: theme.textDim, fontSize: 12 },
  builderInput: { backgroundColor: theme.surface, color: '#FFF', padding: 16, borderRadius: 12, fontSize: 16, marginTop: 10 },
  photoSourceRow: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 20 },
  photoSourceBtn: { alignItems: 'center', backgroundColor: theme.surface, padding: 20, borderRadius: 16, width: '40%' },
  sourceText: { color: theme.textDim, marginTop: 8 },
  
  // NEW POPUP STYLES
  popupCard: { backgroundColor: theme.surface, width: '90%', alignSelf:'center', padding: 24, borderRadius: 24, alignItems: 'center', borderWidth:1, borderColor: theme.surfaceHighlight, marginBottom: '50%' },
  popupTitle: { color: '#FFF', fontSize: 24, fontWeight: 'bold', marginBottom: 8, textAlign: 'center' },
  popupMessage: { color: theme.textDim, fontSize: 18, textAlign: 'center', marginBottom: 24 },
  popupBtn: { backgroundColor: theme.surfaceHighlight, paddingVertical: 12, paddingHorizontal: 32, borderRadius: 30 },
  popupBtnText: { color: '#FFF', fontWeight: 'bold' },
  popupIcon: { width: 64, height: 64, borderRadius: 32, justifyContent: 'center', alignItems: 'center' },

  // HELPER TEXT
  helperText: { color: theme.primary, fontSize: 14, marginBottom: 4, marginTop: 12, fontStyle:'italic' },

  // WORD LIST  
  wordList: { marginTop: 10 },
});

export default styles;
