import { StyleSheet, Platform } from 'react-native';
import { spacing, borderRadius, lightTheme, useTheme } from '../theme';

// Dynamic styles factory - call with theme parameter
export const createStyles = (theme) => StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: theme.bg, paddingTop: Platform.OS === 'android' ? 35 : 0 },
  container: { flex: 1, backgroundColor: theme.bg },
  header: { padding: spacing.xl, paddingBottom: spacing.lg, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  greeting: { fontSize: 26, fontWeight: '800', color: theme.text, marginBottom: spacing.xs },
  statusRowNew: { flexDirection: 'row', marginTop: spacing.xs, flexWrap: 'wrap' },
  statusPill: { flexDirection: 'row', alignItems: 'center', backgroundColor: theme.surface, paddingHorizontal: 10, paddingVertical: spacing.xs, borderRadius: borderRadius.md, marginRight: spacing.sm, marginTop: spacing.xs, borderWidth: 1, borderColor: theme.surfaceHighlight },
  statusText: { color: theme.text, fontSize: 12, marginLeft: 6, fontWeight: '600' },
  profileBadge: { width: 44, height: 44, borderRadius: 22, backgroundColor: theme.surface, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: theme.surfaceHighlight, marginTop: spacing.xs },
  profileText: { color: theme.primary, fontSize: 18, fontWeight: 'bold' },
  onbContainer: { flex: 1, backgroundColor: theme.bg, alignItems: 'center', justifyContent: 'center' },
  onbCard: { width: '85%', backgroundColor: theme.surface, borderRadius: borderRadius.lg, padding: 30, alignItems: 'center' },
  onbTitle: { fontSize: 24, fontWeight: 'bold', color: theme.text, marginBottom: 10 },
  onbText: { fontSize: 16, color: theme.textDim, textAlign: 'center', marginBottom: 20 },
  onbInput: { width: '100%', backgroundColor: theme.surfaceHighlight, color: theme.text, padding: spacing.lg, borderRadius: borderRadius.md, fontSize: 18, marginBottom: 20, textAlign: 'center' },
  onbBtn: { backgroundColor: theme.primary, paddingHorizontal: 32, paddingVertical: spacing.lg, borderRadius: 30, marginTop: 10, alignItems: 'center' },
  onbBtnText: { color: theme.textInverse, fontWeight: 'bold', fontSize: 18 },
  phraseRow: { padding: spacing.lg, borderBottomWidth: 1, borderBottomColor: theme.surfaceHighlight, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  phraseText: { color: theme.text, fontSize: 18 },
  sentenceContainer: { marginHorizontal: spacing.xl, marginBottom: spacing.lg, height: 70, backgroundColor: theme.surface, borderRadius: borderRadius.md, borderWidth: 1, borderColor: theme.primary, flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.md, justifyContent:'space-between' },
  wordBubble: { backgroundColor: theme.surfaceHighlight, borderRadius: borderRadius.md, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, marginRight: spacing.sm, height: 46, justifyContent: 'center' },
  wordText: { color: theme.textInverse, fontSize: 16, fontWeight: '600' },
  placeholderText: { color: theme.textDim, fontStyle: 'italic', marginLeft: spacing.sm },
  editToolbar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: theme.surface, padding: spacing.md, marginHorizontal: spacing.xl, borderRadius: borderRadius.md, marginBottom: spacing.lg, borderWidth: 1, borderColor: theme.primary },
  editInfo: { flex: 1 },
  editLabel: { color: theme.textDim, fontSize: 10, fontWeight: 'bold', textTransform: 'uppercase' },
  editWord: { color: theme.primary, fontSize: 16, fontWeight: 'bold' },
  editActions: { flexDirection: 'row' },
  editBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: theme.surfaceHighlight, justifyContent: 'center', alignItems: 'center', marginLeft: spacing.sm },
  scrollContent: { paddingHorizontal: spacing.xl },
  section: { marginBottom: spacing.xxl },
  label: { color: theme.textDim, fontSize: 12, fontWeight: '700', marginBottom: spacing.md, letterSpacing: 1.2 },
  inputLabel: { color: theme.textDim, fontSize: 12, fontWeight: '700', marginBottom: spacing.sm, letterSpacing: 1.2 },
  
  // GALLERY & GRID FIXES
  catGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  catTile: { width: '48%', backgroundColor: theme.surface, padding: 20, borderRadius: borderRadius.lg, marginBottom: spacing.lg, height: 110, justifyContent: 'space-between' },
  catTitle: { color: theme.text, fontSize: 16, fontWeight: 'bold' },
  galleryBannerLarge: { width: '100%', backgroundColor: theme.primary, borderRadius: borderRadius.lg, padding: spacing.xl, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  galleryIconBadge: { width: 48, height: 48, borderRadius: 24, backgroundColor: 'rgba(255,255,255,0.2)', justifyContent:'center', alignItems:'center', marginRight: spacing.lg },
  galleryBannerText: { color: theme.textInverse, fontSize: 22, fontWeight: 'bold' },
  galleryGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  addPhotoCard: { width: '48%', aspectRatio: 1, backgroundColor: theme.surfaceHighlight, borderRadius: borderRadius.md, justifyContent: 'center', alignItems: 'center', marginBottom: spacing.lg, borderStyle: 'dashed', borderWidth: 2, borderColor: theme.primary },
  photoCard: { width: '48%', aspectRatio: 1, backgroundColor: theme.surface, borderRadius: borderRadius.md, padding: spacing.sm, marginBottom: spacing.lg },
  photoPlaceholder: { flex: 1, borderRadius: borderRadius.sm, marginBottom: spacing.sm },
  photoCaption: { color: theme.text, fontWeight: 'bold', flex: 1, marginRight: spacing.xs },

  listItemRow: { flexDirection: 'row', backgroundColor: theme.surfaceHighlight, padding: spacing.md, borderRadius: borderRadius.sm, marginBottom: spacing.sm, alignItems: 'center' },
  
  // FIXED BOTTOM NAV (NEW)
  fixedBottomNav: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 85, backgroundColor: theme.surface, borderTopWidth: 1, borderTopColor: theme.surfaceHighlight, flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', paddingBottom: 10, paddingHorizontal: 10 },
  navBtn: { alignItems: 'center', flex: 1, paddingVertical: 10 },
  navBtnPrimary: { backgroundColor: theme.primary, borderRadius: borderRadius.md, flex: 1.2, marginHorizontal: 5, paddingVertical: 10, height: 60, justifyContent: 'center', transform: [{translateY: -5}] },
  navIconContainer: { marginBottom: spacing.xs },
  navLabel: { fontSize: 11, color: theme.textDim, fontWeight: '600' },
  navLabelPrimary: { fontSize: 12, color: theme.textInverse, fontWeight: 'bold' },

  outputBar: { position: 'absolute', bottom: 30, left: spacing.xl, right: spacing.xl, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  outputActions: { flexDirection: 'row', backgroundColor: theme.surface, borderRadius: 30, padding: 6, shadowColor: "#000", shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.2, shadowRadius: 20, elevation: 10 },
  outputBtn: { flexDirection: 'row', alignItems: 'center', paddingVertical: spacing.md, paddingHorizontal: spacing.lg, borderRadius: borderRadius.lg, marginLeft: 6 },
  outputBtnTextDark: { color: theme.text, fontWeight: 'bold', marginLeft: 6 },
  outputBtnText: { color: theme.textInverse, fontWeight: 'bold', marginLeft: 6 },
  outputBtnDestructive: { width: 50, height: 50, borderRadius: 25, backgroundColor: theme.surfaceHighlight, justifyContent: 'center', alignItems: 'center' },
  
  emergencyContainer: { flex: 1, backgroundColor: theme.emergencyBg },
  emergencyHeader: { padding: spacing.xl, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  emergencyTitle: { color: theme.danger, fontSize: 24, fontWeight: '900', marginLeft: spacing.lg },
  emergencyCard: { backgroundColor: theme.emergencyCard, padding: 20, borderRadius: borderRadius.md, marginBottom: 20 },
  emLabel: { color: theme.textDim, fontSize: 12, fontWeight: 'bold', marginBottom: spacing.xs },
  emValue: { color: theme.text, fontSize: 20, fontWeight: 'bold', marginBottom: spacing.xs },
  emValueSub: { color: theme.text, fontSize: 16 },
  call112Btn: { backgroundColor: theme.danger, padding: 20, borderRadius: borderRadius.md, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginBottom: spacing.lg },
  callText: { color: theme.textInverse, fontSize: 24, fontWeight: '900', marginLeft: spacing.lg },
  callBtnSmall: { flex:1, backgroundColor: theme.surfaceHighlight, padding: spacing.lg, borderRadius: borderRadius.md, alignItems: 'center', marginRight: 10 },
  callSmallText: { color: theme.textInverse, fontWeight: 'bold', marginTop: spacing.sm },
  medLabel: { color: theme.danger, fontWeight: 'bold', marginTop: 20, marginBottom: spacing.xs },
  medValue: { color: theme.text, fontSize: 16 },
  historyItem: { paddingVertical: spacing.lg, borderBottomWidth: 1, borderBottomColor: theme.surfaceHighlight },
  historyTime: { color: theme.primary, fontSize: 12, marginBottom: spacing.xs },
  historyText: { color: theme.text, fontSize: 16 },
  emptyText: { color: theme.textDim, fontSize: 16, fontStyle: 'italic' },
  aiFullSentenceBtn: { backgroundColor: theme.surface, padding: spacing.lg, borderRadius: borderRadius.md, marginBottom: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  aiFullSentenceText: { color: theme.text, fontSize: 16, fontWeight: '600' },
  aiBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: theme.surfaceHighlight, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs, borderRadius: borderRadius.sm, marginRight: 10 },
  aiBadgeText: { color: theme.textDim, fontWeight: 'bold', fontSize: 10, marginLeft: spacing.xs },
  selectorItem: { alignItems: 'center', marginRight: spacing.xl, opacity: 0.5 },
  selectorItemActive: { opacity: 1 },
  selectorIcon: { width: 60, height: 60, borderRadius: 30, backgroundColor: theme.surfaceHighlight, justifyContent: 'center', alignItems: 'center', marginBottom: spacing.sm },
  selectorLabel: { color: theme.text, fontWeight: 'bold' },
  formLabel: { color: theme.primary, fontWeight: 'bold', marginBottom: spacing.sm, marginTop: spacing.lg },
  inputField: { backgroundColor: theme.surface, color: theme.text, padding: spacing.lg, borderRadius: borderRadius.md, fontSize: 16, marginBottom: spacing.lg, borderWidth: 1, borderColor: theme.surfaceHighlight },
  quickBtn: { backgroundColor: theme.surface, paddingHorizontal: 20, paddingVertical: spacing.lg, borderRadius: borderRadius.md, marginRight: 10, borderWidth:1, borderColor: theme.surfaceHighlight },
  quickText: { color: theme.text, fontWeight:'bold', fontSize: 16 },
  addPhraseBtn: { flexDirection:'row', alignItems:'center', backgroundColor: theme.surfaceHighlight, padding: spacing.lg, borderRadius: borderRadius.md, marginBottom: 20 },
  addPhraseText: { color: theme.textInverse, fontWeight:'bold', marginLeft: 10 },
  catHeaderSmall: { fontSize: 20, fontWeight:'bold', color: theme.text },
  catHeaderBig: { fontSize: 28, fontWeight:'bold', color: theme.text, marginBottom: 20 },
  builderContainerFull: { flex:1, backgroundColor: theme.bg, padding: spacing.xl },
  builderHeader: { flexDirection:'row', justifyContent:'space-between', alignItems:'center', marginBottom: 20 },
  builderPreview: { backgroundColor: theme.surface, minHeight: 80, borderRadius: borderRadius.md, justifyContent:'center', marginBottom: 20, padding: 10 },
  builderWordChip: { backgroundColor: theme.surfaceHighlight, paddingHorizontal: spacing.lg, paddingVertical: spacing.sm, borderRadius: borderRadius.sm, marginHorizontal: spacing.xs },
  aiMagicBtnFull: { backgroundColor: theme.primary, borderRadius: borderRadius.md, padding: spacing.md, flexDirection:'row', justifyContent:'space-between', alignItems:'center', marginBottom: 15 },
  aiMagicTextFull: { fontWeight:'bold', fontSize: 16, color: theme.textInverse },
  suggestionBubble: { backgroundColor: theme.surface, paddingHorizontal: spacing.lg, paddingVertical: spacing.sm, borderRadius: 20, marginRight: spacing.sm, borderWidth:1, borderColor: theme.primary },
  suggestionText: { color: theme.text },
  wordTabs: { flexDirection:'row', marginBottom: 15 },
  wordTab: { flex:1, alignItems:'center', paddingVertical: 10, borderBottomWidth: 2, borderBottomColor: theme.surfaceHighlight },
  wordTabText: { color: theme.textDim, fontWeight:'bold', fontSize: 12 },
  coreWordsGrid: { flexDirection:'row', flexWrap:'wrap', justifyContent:'space-between' },
  coreWordTileLarge: { width:'48%', backgroundColor: theme.surface, padding: 20, borderRadius: borderRadius.md, marginBottom: spacing.md, alignItems:'center' },
  coreWordTextLarge: { color: theme.text, fontSize: 18, fontWeight:'bold' },
  builderInputSmall: { flex:1, backgroundColor: theme.surface, borderRadius: 25, paddingHorizontal: 20, color: theme.text, height: 50 },
  addBtnSmallRound: { width: 50, height: 50, borderRadius: 25, backgroundColor: theme.primary, justifyContent:'center', alignItems:'center', marginLeft: 10 },
  saveBtn: { backgroundColor: theme.primary, padding: spacing.lg, borderRadius: borderRadius.md, alignItems:'center', marginTop: 10 },
  saveBtnText: { fontWeight:'bold', fontSize: 18, color: theme.textInverse },
  fullScreenContainer: { flex:1, backgroundColor: theme.bg, justifyContent:'center', alignItems:'center', padding: 20 },
  fullScreenClose: { position:'absolute', top: 50, right: 30, alignItems:'center' },
  fullScreenContent: { transform: [{ rotate: '90deg'}] },
  fullScreenText: { color: theme.text, fontSize: 50, fontWeight:'bold', textAlign:'center' },
  modalOverlay: { flex:1, backgroundColor:'rgba(0,0,0,0.5)', justifyContent:'flex-end' },
  selectorContainer: { backgroundColor: theme.bg, borderTopLeftRadius: borderRadius.lg, borderTopRightRadius: borderRadius.lg, padding: spacing.xl, maxHeight: '80%' },
  selectorHeader: { flexDirection:'row', justifyContent:'space-between', alignItems:'center', marginBottom: spacing.xl },
  selectorTitle: { color: theme.text, fontSize: 20, fontWeight:'bold' },
  menuItem: { flexDirection:'row', alignItems:'center', paddingVertical: spacing.lg, borderBottomWidth:1, borderBottomColor: theme.surfaceHighlight },
  menuItemTitle: { color: theme.text, fontSize: 18, marginLeft: spacing.lg, fontWeight:'bold' },
  tagContainer: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 10 },
  tagChip: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.md, paddingVertical: 6, borderRadius: 20, backgroundColor: theme.surface, marginRight: spacing.sm, marginBottom: spacing.sm, borderWidth: 1, borderColor: theme.surfaceHighlight },
  tagChipActive: { backgroundColor: theme.primary, borderColor: theme.primary },
  tagText: { color: theme.textDim, fontSize: 12 },
  builderInput: { backgroundColor: theme.surface, color: theme.text, padding: spacing.lg, borderRadius: borderRadius.md, fontSize: 16, marginTop: 10, borderWidth: 1, borderColor: theme.surfaceHighlight },
  photoSourceRow: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 20 },
  photoSourceBtn: { alignItems: 'center', backgroundColor: theme.surface, padding: 20, borderRadius: borderRadius.md, width: '40%' },
  sourceText: { color: theme.textDim, marginTop: spacing.sm },
  
  // NEW POPUP STYLES
  popupCard: { backgroundColor: theme.surface, width: '90%', alignSelf:'center', padding: spacing.xl, borderRadius: borderRadius.lg, alignItems: 'center', borderWidth:1, borderColor: theme.surfaceHighlight, marginBottom: '50%' },
  popupTitle: { color: theme.text, fontSize: 24, fontWeight: 'bold', marginBottom: spacing.sm, textAlign: 'center' },
  popupMessage: { color: theme.textDim, fontSize: 18, textAlign: 'center', marginBottom: spacing.xl },
  popupBtn: { backgroundColor: theme.surfaceHighlight, paddingVertical: spacing.md, paddingHorizontal: 32, borderRadius: 30 },
  popupBtnText: { color: theme.textInverse, fontWeight: 'bold' },
  popupIcon: { width: 64, height: 64, borderRadius: 32, justifyContent: 'center', alignItems: 'center' },

  // HELPER TEXT
  helperText: { color: theme.primary, fontSize: 14, marginBottom: spacing.xs, marginTop: spacing.md, fontStyle:'italic' },

  // WORD LIST  
  wordList: { marginTop: 10 },
});

// Default export for backwards compatibility (uses light theme)
const styles = createStyles(lightTheme);
export default styles;

// Hook for dynamic themed styles
export const useStyles = () => {
  const { theme } = useTheme();
  return createStyles(theme);
};
